FROM node:alpine

# Create app directory
WORKDIR /usr/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

COPY config.js config.js

# Bundle app source
COPY src src

CMD npm run ${ENV}
EXPOSE ${DIRECTOR_LOCAL_PORT}